name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

env:
  COLUMNS: 120

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install {{manager}} and PoeThePoet
      run: pip install {{manager}} poethepoet
    - name: Install dependencies with {{manager}}
      run:
      {%- if manager == "poetry" -%}}
      poetry install
      {%- elif manager == "uv" -%}
      uv sync
      {%- endif %}
    - uses: pre-commit/action@v3.0.0
