[project]
name = "python-template"
version = "0.1.0"
requires-python = ">=3.10.9, <4.0.0"  # note: using <4 is wrong, but ctt requires it.

[dependency-groups]
dev = [
    "copier-template-tester>=2.2.0",
]
