# if not using poethepoet: remove dev dependencies in pyprojext. update black version in github action
# if using poethepoet: remove black github action
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # filesystem
      - id: check-illegal-windows-names
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      # git
      - id: check-added-large-files
      - id: check-merge-conflict
      # secrets
      - id: detect-private-key
      # text in files
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
      # python
      - id: check-ast
      - id: check-docstring-first
      - id: debug-statements
      - id: requirements-txt-fixer
      # filetypes
      - id: check-json
        exclude: ipynb
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      - id: pretty-format-json
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-tabs
  # {{remove if using poethepoet}}
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
      - id: ruff
        alias: ruff-isort
        args: ["--select", "I001", "--fix"]
      # {{ replace black? }}
      - id: ruff-format
      # {{/replace}}
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
      - id: black
  # {keep if using jupyter:forbidden}
  - repo: local
    hooks:
      - id: forbid-ipynb
        name: forbid ipynb
        entry: filenames must not end in .ipynb
        language: fail
        files: '\.ipynb$'
  # {keep if using jupyter:black}
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
      - id: black
      - id: black-jupyter
  # {keep if using jupyter:nbqa}
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-check-ast
      - id: nbqa-black
      - id: nbqa-ruff
  # {keep}
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
  # {{/remove if using poethepoet}}
  # {{remove if not using poethepoet}}
  - repo: local
    hooks:
    # black/ruff-isort using poe
    - id: poe-format
      name: poe-the-poet format
      entry: poe format
      stages: [pre-commit, pre-merge-commit, pre-push, manual]
      language: system
      require_serial: true
      types_or: [python, pyi, jupyter]
    # ruff/mypy using poe
    - id: poe-lint
      name: poe-the-poet lint
      entry: poe lint
      language: system
      types_or: [python, pyi]
      require_serial: true
    # pytest using poe
    - id: poe-test
      name: poe-the-poet test
      entry: poe test
      stages: [pre-commit, pre-merge-commit, pre-push, manual]
      language: system
      pass_filenames: false
      always_run: true
  # {{/remove if not using poethepoet}}
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.4
    hooks:
      - id: poetry-check
